jobs:
- job: conv
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool: 'Linux-CPU'
  steps:
    - template: templates/set-version-number-variables-step.yml

    - task: CmdLine@2
      inputs:
        script: |
          set -e
          sudo apt-get install -y python3-pip
          sudo python3 -m pip install mysql-connector-python
          ln -s /data/models .
          LLVM_PROFILE_FILE="%p.profraw" CFLAGS="-g -fprofile-instr-generate -fcoverage-mapping" CXXFLAGS="-g -fprofile-instr-generate -fcoverage-mapping" CC=clang CXX=clang++  python3 $(Build.SourcesDirectory)/tools/ci_build/build.py --build_dir=$(Build.BinariesDirectory) --config Debug --parallel --skip_submodule_sync --build_shared_lib --enable_onnx_tests
          cd Debug
          LLVM_PROFILE_FILE="testrunner.profraw" ./onnx_test_runner -j 1 -c 2 /data/models
          llvm-profdata merge -sparse  -o ort.profdata *.profraw
          llvm-cov export -summary-only -instr-profile=ort.profdata onnx_test_runner -object onnxruntime_test_all  $(Build.SourcesDirectory)/include/onnxruntime $(Build.SourcesDirectory)/onnxruntime/core $(Build.SourcesDirectory)/onnxruntime/contrib_ops > $(Build.BinariesDirectory)/report.json
        workingDirectory: $(Build.BinariesDirectory)


    - task: CmdLine@2
      displayName: 'Post code coverage data to the Dashboard'
      inputs:
        script: |
          python3 $(Build.SourcesDirectory)/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py  --commit_hash=$(OnnxRuntimeGitCommitHash) --report_file="$(Build.BinariesDirectory)/report.json" --report_url="https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=$(Build.BuildId)"
        workingDirectory: $(Build.BinariesDirectory)
      env: 
        DASHBOARD_MYSQL_ORT_PASSWORD: $(dashboard-mysql-ort-password)

    - template: templates/clean-agent-build-directory-step.yml
